### ISSUE TITLE
Is current version compatible with gedit 3.18(.2)

### ISSUE THREAD

**Issue by elicoidal** [bittner/gedit-reST-plugin#12]
I am testing the plugin in Ubuntu 15.10/Gedit 3.18.2
I am currently stuck as there is no View/Bottom Panel entry available and cannot get the panel displayed

**Comment by bittner** [comment]
Have you tried the [gedit-3.14](https://github.com/bittner/gedit-reST-plugin/tree/gedit-3.14) branch?

If you don't see any error messages please start Gedit from the terminal. Then check what's being printed out on the console when you activate the plugin via Preferences > Plugins.

**Comment by elicoidal** [comment]
@bittner Thanks for the reply. Actually I tried master. I will checkout again and let you know

**Comment by elicoidal** [comment]
after 3.14 checkout, I get the following output:
home/eric/.local/share/gedit/plugins/reST/__init__.py:20: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gedit, WebKit
No bp log location saved, using default.
[000:000] Cpu: 6.42.7, x4, 3500Mhz, 7877MB
[000:000] Computer model: Not available
No bp log location saved, using default.
[000:000] Cpu: 6.42.7, x4, 3500Mhz, 7877MB
[000:000] Computer model: Not available
[000:001] Browser XEmbed support present: 1
[000:001] Browser toolkit is Gtk2.
[000:002] Using Gtk2 toolkit
[000:004] No bp log location saved, using default.
[000:004] Cpu: 6.42.7, x4, 3500Mhz, 7877MB
[000:004] Computer model: Not available
[000:010] No bp log location saved, using default.
[000:010] Cpu: 6.42.7, x4, 3500Mhz, 7877MB
[000:011] Computer model: Not available
[000:011] Browser XEmbed support present: 1
[000:011] Browser toolkit is Gtk2.
[000:011] Using Gtk2 toolkit
Traceback (most recent call last):
  File "/home/eric/.local/share/gedit/plugins/reST/__init__.py", line 37, in do_activate
    self._panel.update_view(self.window)
  File "/home/eric/.local/share/gedit/plugins/reST/restructuredtext.py", line 74, in update_view
    base_uri = parent_window.get_active_document().\
AttributeError: 'NoneType' object has no attribute 'get_uri'

(gedit:5533): Gtk-CRITICAL **: gtk_container_remove: assertion '_gtk_widget_get_parent (widget) == GTK_WIDGET (container) || GTK_IS_ASSISTANT (container) || GTK_IS_ACTION_BAR (container) || GTK_IS_POPOVER_MENU (container)' failed

**Comment by bittner** [comment]
The error message says the `get_location()` returns `None` for some reason on [line 74+](https://github.com/bittner/gedit-reST-plugin/blob/gedit-3.14/reST/restructuredtext.py#L75).

* You do have a document open, don't you?
* What (kind of) document you have open, or more specifically, what is the path or address of the document?
* Do you have the preview panel open?

**Comment by bittner** [comment]
I've tried the plugin on my 14.04.3 box with gedit 3.10.4, and I get the same error.

I've noticed that in gedit the menu option _View_ > _Bottom Panel_ is grayed out. Can you confirm this for your system? This could be what causes the problem.

I'm trying to find a solution on the menu item / bottom panel issue. If you have a clue let me know.

**Comment by elicoidal** [comment]
Hi,
I have restarted my laptop this morning and triggered fresh gedit and still the same message (so no document in edition mode or cache whatsoever).
Surprise!
**First launch** I did not have the menu with following output:
/home/eric/.local/share/gedit/plugins/reST/__init__.py:21: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gedit, WebKit
No bp log location saved, using default.
[000:000] Cpu: 6.42.7, x4, 3500Mhz, 7877MB
[000:000] Computer model: Not available
No bp log location saved, using default.
[000:000] Cpu: 6.42.7, x4, 3500Mhz, 7877MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is Gtk2.
[000:003] Using Gtk2 toolkit
[000:005] No bp log location saved, using default.
[000:006] Cpu: 6.42.7, x4, 3500Mhz, 7877MB
[000:006] Computer model: Not available
[000:011] No bp log location saved, using default.
[000:012] Cpu: 6.42.7, x4, 3500Mhz, 7877MB
[000:012] Computer model: Not available
[000:012] Browser XEmbed support present: 1
[000:012] Browser toolkit is Gtk2.
[000:012] Using Gtk2 toolkit
Traceback (most recent call last):
  File "/home/eric/.local/share/gedit/plugins/reST/__init__.py", line 38, in do_activate
    self._panel.update_view(self.window)
  File "/home/eric/.local/share/gedit/plugins/reST/restructuredtext.py", line 74, in update_view
    base_uri = parent_window.get_active_document().\
AttributeError: 'NoneType' object has no attribute 'get_uri'

**Second launch** I had the menu and the panel showed up with following (similar) output:
/home/eric/.local/share/gedit/plugins/reST/__init__.py:21: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gedit, WebKit
No bp log location saved, using default.
[000:000] Cpu: 6.42.7, x4, 3500Mhz, 7877MB
[000:000] Computer model: Not available
No bp log location saved, using default.
[000:000] Cpu: 6.42.7, x4, 3500Mhz, 7877MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is Gtk2.
[000:001] Using Gtk2 toolkit
[000:004] No bp log location saved, using default.
[000:004] Cpu: 6.42.7, x4, 3500Mhz, 7877MB
[000:004] Computer model: Not available
[000:009] No bp log location saved, using default.
[000:010] Cpu: 6.42.7, x4, 3500Mhz, 7877MB
[000:010] Computer model: Not available
[000:010] Browser XEmbed support present: 1
[000:010] Browser toolkit is Gtk2.
[000:010] Using Gtk2 toolkit
Traceback (most recent call last):
  File "/home/eric/.local/share/gedit/plugins/reST/__init__.py", line 50, in do_update_state
    self._panel.update_view(self.window)
  File "/home/eric/.local/share/gedit/plugins/reST/restructuredtext.py", line 74, in update_view
    base_uri = parent_window.get_active_document().\
AttributeError: 'NoneType' object has no attribute 'get_uri'
Traceback (most recent call last):
  File "/home/eric/.local/share/gedit/plugins/reST/__init__.py", line 50, in do_update_state
    self._panel.update_view(self.window)
  File "/home/eric/.local/share/gedit/plugins/reST/restructuredtext.py", line 74, in update_view
    base_uri = parent_window.get_active_document().\
AttributeError: 'NoneType' object has no attribute 'get_uri'

Bottom panel was working properly actually.
Python console is not activated.
One of my dev suggested to follow the help message "gi.require_version('WebKit', '3.0')" and fix the __init__.py before import (sorry we do not have time to test and help more here).
There might be a mismatch version of webkit ( 2.0 <> 3.0)

**Comment by bittner** [comment]
I've just pushed [some changes](https://github.com/bittner/gedit-reST-plugin/commit/47190c39ac868813d31e9b598adabf70441a94ee) to the `gedit-3.14` branch to allow some cross-version compatibility. Please try installing the plugin again. It's now working for me.

**Comment by elicoidal** [comment]
I have tested it and (still) works for me.
Thanks!

**Comment by bittner** [comment]
I've merged the `gedit-3.14` branch into `master` now.

Enjoy the working, although feature-reduced, plugin!

**Comment by elicoidal** [comment]
Thanks for the support and the contribution :)
