### ISSUE TITLE
"Failed to load" error with GEdit 3.10.4

### ISSUE THREAD

**Issue by ldesousa** [bittner/gedit-reST-plugin#14]
I just installed this plugin on Gedit 3.10.4 (Ubuntu 14.04). When I activate it from the Preferences dialogue, I receive this error:

![gedit](https://cloud.githubusercontent.com/assets/1137878/16034408/ed566a76-3211-11e6-83b7-e71518a64850.png)

**Comment by bittner** [comment]
Please see issues #13, #9 and #6. This looks like a duplicate.

**Comment by ldesousa** [comment]
This issue seems unrelated to issues #6, #9 or #13:

 - I am using GEdit 3.10.4, not 3.14.

 - I do have the `gir1.2-webkit-3.0 package` installed:
```
$ dpkg -l | grep gir1.2-webkit-3.0
ii  gir1.2-webkit-3.0                                           2.4.10-0ubuntu0.14.04.1                             amd64        Web content engine library for GTK+ - GObject introspection data
```

 - As so `doctutils`:
```
$ dpkg -l | grep docutils
ii  docutils-common                                             0.11-3                                              all          text processing system for reStructuredText - common data
ii  docutils-doc                                                0.11-3                                              all          text processing system for reStructuredText - documentation
```

 - The plugin is present in the recommended folder:
```
$ ls -la /usr/lib/gedit/plugins/
total 32
drwxr-xr-x 5 root root 4096 Jun 14 09:18 .
drwxr-xr-x 3 root root 4096 Jan  7 09:49 ..
drwxr-xr-x 7 root root 4096 Feb 10 14:19 advancedfind
-rw-r--r-- 1 root root  820 Jan 11 08:51 advancedfind.plugin
drwxr-xr-x 7 root root 4096 Jan  7 09:49 latex
-rw-r--r-- 1 root root 2996 Okt 22  2013 latex.plugin
drwxr-xr-x 2 root root 4096 Jun 14 09:18 reST
-rw-r--r-- 1 root root  360 Jun 14 09:18 reST.plugin
```

```
$ ls -la /usr/lib/gedit/plugins/reST
total 92
drwxr-xr-x 2 root root  4096 Jun 14 09:18 .
drwxr-xr-x 5 root root  4096 Jun 14 09:18 ..
-rw-r--r-- 1 root root 35501 Jun 14 09:18 default.odt
-rw-r--r-- 1 root root  4421 Jun 14 09:18 default.sty
-rw-r--r-- 1 root root  1903 Jun 14 09:18 __init__.py
-rw-r--r-- 1 root root  5549 Jun 14 09:18 makeTable.py
-rw-r--r-- 1 root root  2310 Jun 14 09:18 RegisterPygment.py
-rw-r--r-- 1 root root  6879 Jun 14 09:18 restructuredtext.css
-rw-r--r-- 1 root root  2877 Jun 14 09:18 restructuredtext.py
-rw-r--r-- 1 root root  1360 Jun 14 09:18 to_html.py
-rw-r--r-- 1 root root  2929 Jun 14 09:18 to_odt.py
-rw-r--r-- 1 root root  2370 Jun 14 09:18 to_tex.py
```

**Comment by bittner** [comment]
Please start gedit from the Terminal, then activate the plugin (so that you reproduce the screen shot above) and post the output (Python exception stack trace) here.

**Comment by ldesousa** [comment]
Here is the terminal output:

```
Traceback (most recent call last):
  File "/usr/lib/gedit/plugins/reST/__init__.py", line 22, in <module>
    from .restructuredtext import RestructuredtextHtmlPanel
  File "/usr/lib/gedit/plugins/reST/restructuredtext.py", line 20, in <module>
    from docutils.core import publish_parts
ImportError: No module named 'docutils'

(gedit:27377): libpeas-WARNING **: Error loading plugin 'reST'
```

**Comment by bittner** [comment]
There you go:
``` python
ImportError: No module named 'docutils'
```
Install `python3-docutils` and you should be all set. See the [README](https://github.com/bittner/gedit-reST-plugin#dependencies).
