### ISSUE TITLE
Fails to load on gedit 46.1; Manjaro 23.1.0

### ISSUE THREAD

**Issue by javadr** [bittner/gedit-reST-plugin#28]
When running `gedit`, I encounter the following error when configuring the settings to display the review on the side panel. However, it's worth noting that everything functions correctly when the default setting is to display the output in the bottom pane. It appears that in the latest update of GNOME, some functions have been either removed or renamed.

The error I got is:

```python
WARNING:reST:Falling back to old implementation. Reason: 'PanelContainer' object has no attribute 'add_titled'
Traceback (most recent call last):
File "/home/javad/.local/share/gedit/plugins/reST/__init__.py", line 86, in add_container_to_panel
self.display_panel.add_titled(self.html_container, panel_name,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PanelContainer' object has no attribute 'add_titled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/javad/.local/share/gedit/plugins/reST/__init__.py", line 63, in do_activate
self.add_container_to_panel()
File "/home/javad/.local/share/gedit/plugins/reST/__init__.py", line 90, in add_container_to_panel
self.display_panel.add_item(self.html_container, panel_name,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PanelContainer' object has no attribute 'add_item'
Traceback (most recent call last):
File "/home/javad/.local/share/gedit/plugins/reST/__init__.py", line 110, in do_update_state
self.html_container.update_view()
File "/home/javad/.local/share/gedit/plugins/reST/restructuredtext.py", line 125, in update_view
if self.preview_visible():
^^^^^^^^^^^^^^^^^^^^^^
File "/home/javad/.local/share/gedit/plugins/reST/restructuredtext.py", line 118, in preview_visible
self.panel.get_visible_child() == self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PanelContainer' object has no attribute 'get_visible_child'
Traceback (most recent call last):
File "/home/javad/.local/share/gedit/plugins/reST/__init__.py", line 110, in do_update_state
self.html_container.update_view()
File "/home/javad/.local/share/gedit/plugins/reST/restructuredtext.py", line 125, in update_view
if self.preview_visible():
^^^^^^^^^^^^^^^^^^^^^^
File "/home/javad/.local/share/gedit/plugins/reST/restructuredtext.py", line 118, in preview_visible
self.panel.get_visible_child() == self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PanelContainer' object has no attribute 'get_visible_child'
Traceback (most recent call last):
File "/home/javad/.local/share/gedit/plugins/reST/__init__.py", line 110, in do_update_state
self.html_container.update_view()
File "/home/javad/.local/share/gedit/plugins/reST/restructuredtext.py", line 125, in update_view
if self.preview_visible():
^^^^^^^^^^^^^^^^^^^^^^
File "/home/javad/.local/share/gedit/plugins/reST/restructuredtext.py", line 118, in preview_visible
self.panel.get_visible_child() == self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PanelContainer' object has no attribute 'get_visible_child'
```

**Comment by bittner** [comment]
Thank you so much for the valuable feedback!

Can you share which Linux distribution you're running and which is your version of GNOME (e.g. `lsb_release -a` and/or Desktop > *Settings* > *About*)?

I've tried to investigate how to come up with a test suite that runs against all current versions of GNOME (see #27), which would let us detect such cases early on, but unfortunately I've not been successful so far. If anyone knows or has a good idea I'd be happy to know!

**Comment by bittner** [comment]
> Can you share which Linux distribution you're running

Oh, it's in the title: Manjaro 23.1.0, I apologize! GNOME version might still be interesting.

### Note to self

Just for the sake of documentation, I'm running gedit 41.0 on Ubuntu 22.04.3 LTS with GNOME 42.9, and the issues do not occur yet. Though, I get the following stack trace when pressing the <kbd>Preferences</kbd> button in the "Plugins" tab.

```python
Traceback (most recent call last):
  File "/home/peter/.local/share/gedit/plugins/gedit-reST-plugin/reST/__init__.py", line 139, in do_create_configure_widget
    return config_widget.configure_widget()
  File "/home/peter/.local/share/gedit/plugins/gedit-reST-plugin/reST/config.py", line 87, in configure_widget
    self._ui.add_from_file(self._ui_path)
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/peter/.local/share/gedit/plugins/reST/config.ui”: No such file or directory (4)

(gedit:413244): libpeas-gtk-CRITICAL **: 11:46:50.388: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed
```

**Comment by javadr** [comment]
Thanks for your prompt reply. 
I hope this helps you find out the issue. 
If you need any other information, feel free to let me know to give you it. 

```bash
$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        23.1.0
Codename:       Vulcan
```

![image](https://github.com/bittner/gedit-reST-plugin/assets/1178221/bbf92af6-f5b3-44b2-b3ce-537019043e09)

**Comment by javadr** [comment]
Have you seen https://gedit-technology.net/developer-docs/gedit/api-breaks.html?
It seems some methods have been removed or renamed!

**Comment by javadr** [comment]
API Breaks has been moved to the following address:
https://gedit-technology.github.io/developer-docs/gedit/api-breaks.html

**Comment by bittner** [comment]
Thanks @javadr for keeping the development information updated! I'll try to get around fixing the issue after Christmas or New Year. Thank you for your patience!

**Comment by bittner** [comment]
I managed to install gedit 46.1 [from flathub](https://flathub.org/apps/org.gnome.gedit), but I can't get it to detect and load the plugin. Neither of the directories as of the [installation instructions](https://github.com/bittner/gedit-reST-plugin/blob/main/README.rst#installation) in the README seem to be considered.

How did you install the plugin? Did you do anything different?

**Comment by bittner** [comment]
When installed with flatpak the plugins directory is in `~/.var/app/org.gnome.gedit/data/gedit/plugins/`. I'll update the README to reflect this.

See also: https://gitlab.gnome.org/GNOME/gedit/-/issues/301
